### ISSUE TITLE
Problem with freetype internal headers during build OpenJDK7 on MacOS X

### ISSUE THREAD

**Issue by Spikhalskiy** [hgomez/obuildfactory#39]
I use [this instruction](https://github.com/hgomez/obuildfactory/wiki/Building-and-Packaging-OpenJDK7-for-OSX) to build OpenJDK7 with Mac OS Yosemite and XCode 6.1.1 + command line tools.

During first build I got

```
rmdir: /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/include/freetype2/freetype/internal: No such file or directory
make: [install] Error 1 (ignored)
/usr/bin/install -c -m 644 ./builds/unix/ft2unix.h \
          /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/include/ft2build.h
/usr/bin/install -c -m 644 ./builds/unix/ftconfig.h                        \
          /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/include/freetype2/freetype/config/ftconfig.h
/usr/bin/install -c -m 644 /Users/dmitry/Projects/jdk/obuildfactory/freetype-2.4.10/objs/ftmodule.h                          \
          /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/include/freetype2/freetype/config/ftmodule.h
/usr/bin/install -c -m 755 ./builds/unix/freetype-config \
          /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/bin/freetype-config
/usr/bin/install -c -m 644 ./builds/unix/freetype2.m4 \
          /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/share/aclocal/freetype2.m4
/usr/bin/install -c -m 644 ./builds/unix/freetype2.pc \
          /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/lib/pkgconfig/freetype2.pc
cp: /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/lib/libfreetype.dylib and /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/lib/libfreetype.6.dylib are identical (not copied).
```
error and that's all.

Directory /Users/dmitry/Projects/jdk/obuildfactory/OBF_DROP_DIR/freetype/include/freetype2/freetype/internal doesn't exists, it's right.

If try build once more without any clean, I get

```
ERROR: The Compiler version is undefined. 
 
ERROR: FreeType version  2.3.0  or higher is required. 
 /bin/mkdir -p /Users/dmitry/Projects/jdk/obuildfactory/sources/openjdk7/build/macosx-x86_64/btbins
rm -f /Users/dmitry/Projects/jdk/obuildfactory/sources/openjdk7/build/macosx-x86_64/btbins/freetype_versioncheck
Failed to build freetypecheck.
```

**Comment by hgomez** [comment]
I dont have osx machines anymore.
I cannot help :(

**Comment by wyatt8740** [comment]
I can try. And if you just need a binary, I have a built openJDK 7 for OSX 10.6 and up. Let me know if you'd like a link.

Do you have any other freetype installed from macports/fink/brew?

**Comment by hgomez** [comment]
I left OSX land 2 years ago, so I cannot tell ;/

**Comment by wyatt8740** [comment]
would it be okay if I uploaded my JDK 7 binaries for OSX 10.6 and up? JDK 8 doesn't build for OSX 10.6, but I think a lot of people would like binaries.

**Comment by hgomez** [comment]
To upload binaries, I would suggest to use Bintray.
GitHub is for code :)

**Comment by wyatt8740** [comment]
yeah, I was thinking on some other site, too.

**Comment by panych** [comment]
:+1: for this issue

**Comment by hgomez** [comment]
Guys, I don't have OSX boxes anymore so you should build and deploy binaries on your side.
Closing this since I cannot do more ;(

**Comment by jirutka** [comment]
The instructions for OS X are outdated. I wanted to update it, but doesn’t have a time yet. I hope that this week…

**Comment by wyatt8740** [comment]
If someone does want my 10.7 OSX binaries (they are about a year old, 22 June 2014), here you go.
https://bintray.com/wyatt8740/generic/openjdk7-sdk-osx-10.6/view

**Comment by wyatt8740** [comment]
Also, hgomez, what about [OSXCROSS](https://github.com/tpoechtrager/osxcross)? Could you use that to build for OS X? I've got an iOS toolchain in Linux, and I'd expect that this is no different.

**Comment by sfdevguy** [comment]
I'm running OS X 10.10.4. The binaries you shared worked for me. Thank you, @wyatt8740!

**Comment by wyatt8740** [comment]
@sfdevguy Good. I'd make a more recent one, but builds have been broken for some time for me. :\
Glad I could help, though! :D

**Comment by ihaolin** [comment]
I have met the same problem，could someone helps?

**Comment by whvirgil2015** [comment]
I met this problem too, any useful tips? I just found a solution for OpenJDK8  by http://gvsmirnov.ru/blog/tech/2014/02/07/building-openjdk-8-on-osx-maverick.html

**Comment by clevertension** [comment]
this is about freetype make file error, you can modify the file
**freetype-x.x.x/builds/unix/install.mk**
for example:  freetype-2.4.10/builds/unix/install.mk
and add this line to mkdir
**$(DESTDIR)$(includedir)/freetype2/freetype/internal  \**


![qq20161230-0](https://cloud.githubusercontent.com/assets/346723/21567199/38c5cc84-cee5-11e6-8671-952db3f52199.png)
