### ISSUE TITLE
Provides section

### ISSUE THREAD

**Issue by radekg** [hgomez/obuildfactory#46]
Hi there, great project, so it seems. Just one thing I am wondering though: any reason why the `Provides` are not set? Say I have a package which depends on `java-runtime-headless`, if I install openjdk from the result of the build of this project:

```
root@647262d44332:/tmp# grep-status -FProvides,Package -sPackage,Provides,Status java-runtime-headless
root@647262d44332:/tmp#
```

Installing `openjdk-8-jdk` from `openjdk-r/ppa`, the same command:

```
root@647262d44332:/tmp# grep-status -FProvides,Package -sPackage,Provides,Status java-runtime-headless
Package: openjdk-8-jre-headless
Provides: java-runtime-headless, java2-runtime-headless, java5-runtime-headless, java6-runtime-headless, java7-runtime-headless, java8-runtime-headless
Status: install ok installed
```

**Comment by hgomez** [comment]
DEB or RPM ?

**Comment by radekg** [comment]
DEB, sorry, should've mention...

**Comment by hgomez** [comment]
ok.

For DEB, I use FPM as I'm not a DEB packager specialist.

**Comment by radekg** [comment]
I see if I could do a pr...

**Comment by hgomez** [comment]
BTW, take a care 

Obuildfactory JDK is not deployed on system location (/usr/...) as it's more an alternative Java Environment for tests purposes and to avoid collisions with distro Java packages

**Comment by radekg** [comment]
Yeah, I noticed, would you mind a configurable (with an env variable) output directory?

**Comment by hgomez** [comment]
If configurable is to have a 'system' wide mode, it would requires more works, for example alternatives use, which is not the target for Obuildfactory packages

**Comment by radekg** [comment]
Ok, let's skip alternatives. I can do with linking and setting `JAVA_HOME`. However, `Provides` is the minimum. Does that sound ok?

**Comment by hgomez** [comment]
Provides is ok yes :)

**Comment by hgomez** [comment]
PR ?

**Comment by hgomez** [comment]
No PR, closing ticket
