### ISSUE TITLE
Java version mismatch when building JFX 8u122

### ISSUE THREAD

**Issue by dahl777** [hgomez/obuildfactory#52]
I'm trying to build 8u122 but I get an error that the minimum version needs to be 1.8.0_40.
How do I fix this?

 XUSE_NEW_BUILD_SYSTEM=true XBUILD=true XGRADLE=~/gradle-1.8/bin/gradle ./obuildfactory/openjdk8-javafx/linux/standalone-job.sh

Execution failed for task ':verifyJava'.

> FAIL: java version mismatch: JDK version (1.8.0) < minimum version (1.8.0_40)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.543 secs

**Comment by hgomez** [comment]
Update your java 8 to latest
