### ISSUE TITLE
build jdk 1.8 with newer TLS defaults

### ISSUE THREAD

**Issue by paleozogt** [hgomez/obuildfactory#60]
The JDK 8 builds on bintray ([for example](https://dl.bintray.com/hgomez/obuildfactory-centos5-x86-64/)) are built with `b112`.

According to [Oracle](https://blogs.oracle.com/java-platform-group/jdk-8-will-use-tls-12-as-default),  `b122` introduced TLS 1.2 as the default.

Can we get a newer JDK 8 build on bintray that uses the latest TLS default?

**Comment by paleozogt** [comment]
For reference, the old TLS default causes trouble [like this](https://github.com/gradle/gradle/issues/5940).

**Comment by hgomez** [comment]
For which distributions do you need JDK 8 binaries ?

**Comment by paleozogt** [comment]
@hgomez Centos 5, x86_64

**Comment by hgomez** [comment]
@paleozogt obuildfactory goal was to allow people build their own OpenJDK. Some were produced as an example. Do you have CentOS 5 system available so you could rebuild OpenJDK ?

**Comment by hgomez** [comment]
No answer for a long time, closed
